-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 11:26:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `AERONAVE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AERONAVE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AERONAVE` (
  `ID_AERONAVE` INT NOT NULL AUTO_INCREMENT,
  `MODELO` VARCHAR(45) NOT NULL,
  `CAPACIDADE` INT NOT NULL,
  `MATRICULA` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_AERONAVE`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PASSAGEIRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PASSAGEIRO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PASSAGEIRO` (
  `ID_PASSAGEIRO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(15) NULL,
  PRIMARY KEY (`ID_PASSAGEIRO`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CPF_UNIQUE` ON `PASSAGEIRO` (`CPF` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VOO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VOO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VOO` (
  `ID_VOO` INT NOT NULL AUTO_INCREMENT,
  `CODIGO_VOO` VARCHAR(10) NOT NULL,
  `ORIGEM` CHAR(3) NOT NULL,
  `DESTINO` CHAR(3) NOT NULL,
  `DATA_HORA_PARTIDA` DATETIME NOT NULL,
  `DATA_HORA_CHEGADA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_VOO`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
